# Generated by Django 4.2.4 on 2023-08-04 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('positions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='availability',
            field=models.DateField(),
        ),
    ]
